In [5]:
import pandas as pd
df=pd.DataFrame({'Hoten':["Nguyễn Văn A",  
    "Trần Thị B",  
    "Lê Văn C",  
    "Phạm Thị D",  
    "Vũ Văn E",  
    "Hoàng Thị F",  
    "Đặng Văn G",  
    "Ngô Thị H",  
    "Bùi Văn I",  
    "Dương Thị J"],'Tuoi':[20,21,22,23,24,25,26,27,28,29],'Gioitinh':['Nam','Nữ','Nam','Nữ','Nam','Nữ','Nam','Nữ','Nam','Nữ']})
df

          Hoten  Tuoi Gioitinh
0  Nguyễn Văn A    20      Nam
1    Trần Thị B    21       Nữ
2      Lê Văn C    22      Nam
3    Phạm Thị D    23       Nữ
4      Vũ Văn E    24      Nam
5   Hoàng Thị F    25       Nữ
6    Đặng Văn G    26      Nam
7     Ngô Thị H    27       Nữ
8     Bùi Văn I    28      Nam
9   Dương Thị J    29       Nữ

In [6]:
#Hiển thi các dòng có dữ liệu trùng
A="Thị"
df[df['Hoten'].str.contains(A)]

         Hoten  Tuoi Gioitinh
1   Trần Thị B    21       Nữ
3   Phạm Thị D    23       Nữ
5  Hoàng Thị F    25       Nữ
7    Ngô Thị H    27       Nữ
9  Dương Thị J    29       Nữ